FROM node:22-alpine

RUN npm install -g pnpm@11.1.1

WORKDIR /app

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY prisma ./prisma
RUN pnpm install --fetch-timeout 300000 --fetch-retries 5

COPY . .

EXPOSE 3001
